### ISSUE TITLE
Using MUI-styled apprun component in WebComponent (with shadow DOM)

### ISSUE THREAD

**Issue by jow1** [yysun/apprun#146]
Hi,

I´m using apprun in a React+Typescript application. I want to build WebComponents that make use of apprun along with React as a rendering engine.
The surrounding React app starts the internal apprun component. Inside the apprun component I´m using MUIv5 components, styled with a MUI theme.

However, I´m unable to support MUIv5 styling in my internal apprun component. 

As soon as I use an apprun component in a shadow DOM (WebComponent) (example 2), the styles are not longer available.
In a common apprun project setup without a shadow DOM (and without a WebComponent) (example 1) it works perfectly.

*example 1:*
<img width="1603" alt="expected_view" src="https://github.com/user-attachments/assets/d71d51e2-5c31-47d5-ba80-62951daf7932">

*example 2:*
<img width="835" alt="received_view" src="https://github.com/user-attachments/assets/04b86279-64cd-4211-ab6b-747ecd2750f4">

I attached source code, which contains a closer description of the problem. The top view shows the expected result (example 1) and the bottom view is the achieved result (example 2).

*source code:*
[AppRunMuiExample.tar.gz](https://github.com/user-attachments/files/17190331/AppRunMuiExample.tar.gz)

Thx for your help.

**Comment by yysun** [comment]
You can convert the AppRun Component to React component and use in the web component directly. The fix is attached.
[src.zip](https://github.com/user-attachments/files/17197535/src.zip)

BTW, two more tips:
* I added a style to div#content-area to stack the two examples vertically. 
* And lastly, you can start the component on an element. No need to mount then fire a start event.
