### ISSUE TITLE
Roadmap for Apprun

### ISSUE THREAD

**Issue by Maxximus007** [yysun/apprun#33]
Hi, 

Thank you for creating Apprun. Have been following your creation with great interest recently. Love the clean way and no boilerplate.

You have done quite a bit on the documentation side as well, helping to get a better understanding of Apprun. Sure, a lot more could be added in the future. I've also seen a lot of different approaches and versions.

I'm at the beginning of exploring the possibilities for real use, and still in doubt choosing between Apprun or Hyperapp (mainly because of larger userbase and contributors). 

What might be helpful would be a roadmap, to get a better grasp of the future of Apprun. Perhaps you can find the time to add a few lines about it in the docs? It can help as well to attract new users.

Regards.

**Comment by yysun** [comment]
@Maxximus007 Thank you for your interests in AppRun. 

Great suggestion to add roadmap to the docs. I will add it.

We have been using AppRun in production. We open-sourced it in order to verify the ideas and improve it with the developer community. It is a long-term and ambitious project to deliver a tool for developing applications that can be fast to market, reliable and performant. We have received many positive feedbacks. 

Current I am writing a book for AppRun that has [30 examples](https://github.com/yysun/apprun-apress-book). The book will be published by [Apress](https://www.apress.com) soon. The publisher liked AppRun. The book will help spread the project. I will re-work on the documentation once finished writing the book.

AppRun provides many choices for different project needs. E.g., You can include AppRun in a script tag and use it with JavaScript for small apps. Or you can compile and bundle AppRun with TypeScript code for large apps. Then, there is the global application approach (like Elm/Hyperapp) vs the component-based approach (like React/Redux, but [different](https://medium.com/@yiyisun/redux-vs-the-react-context-api-vs-apprun-f324bee8cbbf)). Also choices for targeting ES5/ES6/Web component, using AppRun as external module/ ES6 modules, server-side rendering ... The goal is to allow developers to use AppRun the way best for their projects.

If there is anything I can clarify and help you choose the technology, let me know.

**Comment by Maxximus007** [comment]
Thank you for your swift and extensive answer. I missed your latest article on Medium, that was very helpful to show the Apprun component approach, clearly a refreshing take on the subject.

Very interested in your upcoming book, hope we can pre-order soon.

The many choices that Apprun provides are excellent, but on the same time choosing the right one is not that easy.

For myself, for years working in a PHP/JQuery environment the possibilities in the JS world are vast and quickly shifting, to say the least. 
But after looking at Vue/React, the Apprun vision seems to fit me quite well, with a backend in [AdonisJS](https://adonisjs.com/). Perhaps at first combining it in their view layer [Edge](https://edge.adonisjs.com/docs/getting-started).

Looking forward to your book and Apprun articles in the near future!

**Comment by Maxximus007** [comment]
Great to see the announcement of your book on [Apress](https://www.apress.com/gp/book/9781484240687)! Since it's currently not yet possible to order, would you share the estimated ETA?

**Comment by yysun** [comment]
@Maxximus007, probably a couple of months. It is being reviewed and edited now. The cover is ready though :)

![img_0705](https://user-images.githubusercontent.com/170547/45527587-70d30100-b7aa-11e8-999d-d5c794df9fc4.JPG)
